# Generated by Django 5.1.1 on 2024-09-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foster",
            fields=[
                (
                    "fosterID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fosterName", models.CharField(max_length=50)),
                ("fosterStreet", models.CharField(max_length=50)),
                ("fosterCity", models.CharField(max_length=50)),
                ("fosterState", models.CharField(max_length=2)),
                ("fosterZip", models.CharField(max_length=5)),
                ("fosterEmail", models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "orgID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("orgName", models.CharField(max_length=50)),
                ("orgContact", models.CharField(max_length=50)),
                ("orgStreet", models.CharField(max_length=50)),
                ("orgCity", models.CharField(max_length=50)),
                ("orgState", models.CharField(max_length=2)),
                ("orgZip", models.CharField(max_length=5)),
                ("orgEmail", models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "petID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("petMicrochipID", models.CharField(max_length=50)),
                ("petName", models.CharField(max_length=50)),
                ("petType", models.CharField(max_length=10)),
                ("petSex", models.CharField(max_length=50)),
                ("petDOB", models.DateField()),
                ("petSpayNeuter", models.CharField(max_length=10)),
                ("petStatus", models.CharField(max_length=15)),
                ("petLocation", models.CharField(max_length=50)),
                ("petImage", models.FileField(upload_to="")),
                ("petRecords", models.FileField(upload_to="")),
                ("petBio", models.CharField(max_length=5000)),
                (
                    "petFoster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetTracker.foster",
                    ),
                ),
                (
                    "petOrganization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetTracker.organization",
                    ),
                ),
            ],
        ),
    ]
