# Generated by Django 5.1.1 on 2024-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetTracker", "0002_remove_pet_petlocation_alter_foster_fosterid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foster",
            name="orgPhone",
            field=models.CharField(default=5555555555, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="orgPhone",
            field=models.CharField(default="5555555555", max_length=10),
            preserve_default=False,
        ),
    ]
